spring.application.name=ms-pedido
server.port=8082
server.servlet.context-path=/pedidoMs

# Configuración base de datos postgreSQL PEDIDOS
spring.datasource.url=jdbc:postgresql://localhost:5433/pedidos_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIÓN DE JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Configuracion base de datos MongoDB CARRITO
spring.mongodb.uri=mongodb://localhost:27018/carrito_db
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# CONFIGURACIÓN SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.packages-to-scan=com.seminario.ms_pedido.controller
springdoc.show-actuator=true

# CONFIGURACIÓN DE CIRCUIT BREAKER (Resilience4j)
resilience4j.circuitbreaker.instances.catalogoClient.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.catalogoClient.slidingWindowSize=10
resilience4j.circuitbreaker.instances.catalogoClient.failureRateThreshold=50.0
resilience4j.circuitbreaker.instances.catalogoClient.slowCallRateThreshold=50.0
resilience4j.circuitbreaker.instances.catalogoClient.slowCallDurationThreshold=2000
resilience4j.circuitbreaker.instances.catalogoClient.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.catalogoClient.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.instances.catalogoClient.waitDurationInOpenState=10000

# CONFIGURACIÓN DE REINTENTOS
resilience4j.retry.instances.catalogoClient.maxAttempts=3
resilience4j.retry.instances.catalogoClient.waitDuration=1000
resilience4j.retry.instances.catalogoClient.retryExceptions=java.io.IOException,java.net.SocketTimeoutException,org.springframework.web.client.ResourceAccessException