spring.application.name=ms-pago
server.port=8083
server.servlet.context-path=/pagoMs

# Configuración base de datos postgreSQL PAGO
spring.datasource.url=jdbc:postgresql://localhost:5434/pago_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIÓN DE JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CONFIGURACIÓN SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.packages-to-scan=com.seminario.ms_pago.controller
springdoc.show-actuator=true

# CONFIGURACIÓN DE MICROSERVICIOS EXTERNOS
usuarios.ms.url=http://localhost:8080
catalogo.ms.url=http://localhost:8081
pedido.ms.url=http://localhost:8082

# CONFIGURACIÓN JWT
jwt.secret=${JWT_SECRET_KEY:c2VjcmV0b19zdXBlcl9segdyb19wYXJhX2Rlc2YXJyb2xsb19lbiVsYWN1bA==}

# CONFIGURACION MERCADO PAGO
mercadopago.access.token=APP_USR-1171197836034263-021817-d497fb8716be8667e8c9a50829ada9fc-3211823743