spring.application.name=ms-catalogo
server.port=8081
server.servlet.context-path=/catalogoMs

# CONFIGURACIÓN DE LA BASE DE DATOS 
spring.mongodb.uri=mongodb://localhost:27017/catalogo_db
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# CONFIGURACIÓN SWAGGER
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.packages-to-scan=com.seminario.ms_catalogo.controller
springdoc.show-actuator=true

# CONFIGURACIÓN DE MICROSERVICIOS EXTERNOS
usuarios.ms.url=http://localhost:8080
pedido.ms.url=http://localhost:8082

# CONFIGURACIÓN JWT
jwt.secret=${JWT_SECRET_KEY:c2VjcmV0b19zdXBlcl9segdyb19wYXJhX2Rlc2YXJyb2xsb19lbiVsYWN1bA==}