services:
# --- BASE DE DATOS USUARIOS (SQL) ---
  usuario-db:
    image: postgres:15-alpine
    container_name: usuario-db
    ports:
      - "5431:5432" 
    environment:
      - POSTGRES_DB=usuarios_db      # La BD se crea sola con este nombre
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/data/usuarios:/var/lib/postgresql/data
    networks:
      - app-network

# --- BASE DE DATOS CATÁLOGO (NoSQL) ---
  catalogo-db:
    image: mongo:latest
    container_name: catalogo-db
    ports:
      - "27017:27017" 
    volumes:
      - ./docker/data/catalogo:/data/db 
    networks:
      - app-network

# --- BASE DE DATOS PEDIDOS (SQL) ---
  pedido-db:
    image: postgres:15-alpine
    container_name: pedido-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=pedidos_db      # La BD se crea sola con este nombre
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/data/pedidos:/var/lib/postgresql/data
    networks:
      - app-network

# --- BASE DE DATOS CARRITO (NoSQL) ---
  carrito-db:
    image: mongo:latest
    container_name: carrito-db
    ports:
      - "27018:27017" 
    volumes:
      - ./docker/data/carrito:/data/db 
    networks:
      - app-network

# --- BASE DE DATOS NOTIFICACIONES (NoSQL) ---
  notificaciones-db:
    image: mongo:latest
    container_name: notificaciones-db
    ports:
      - "27019:27017" 
    volumes:
      - ./docker/data/notificaciones:/data/db 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge