server:
  port: 8090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ms-pedido-ws
          uri: ws://localhost:8082
          predicates:
            - Path=/pedidoMs/ws-notifications/**
            - Header=Upgrade, websocket
        - id: ms-usuarios
          uri: http://localhost:8080
          predicates:
            - Path=/usuariosMs/**
        - id: ms-catalogo
          uri: http://localhost:8081
          predicates:
            - Path=/catalogoMs/**
        - id: ms-pedido
          uri: http://localhost:8082
          predicates:
            - Path=/pedidoMs/**
        - id: ms-pago
          uri: http://localhost:8083
          predicates:
            - Path=/pagoMs/**